# Generated by Django 5.2.11 on 2026-03-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('job_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-Site'), ('hybrid', 'Hybrid')], max_length=30)),
                ('vacancy', models.IntegerField()),
                ('category', models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time'), ('intern', 'Internship'), ('contract', 'Contractual')], max_length=30)),
                ('job_description', models.TextField()),
                ('skills', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
