# Generated by Django 6.0.2 on 2026-02-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('job_location', models.CharField(max_length=100)),
                ('vacancy', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills_required', models.TextField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
