# Generated by Django 5.2.11 on 2026-03-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('job_location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100, null=True)),
                ('vacancy', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('skills', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
