# Generated by Django 6.0.2 on 2026-02-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='post_date',
            new_name='deadline',
        ),
    ]
