# Generated by Django 6.0.2 on 2026-02-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_rename_post_date_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
